apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-dashboards
  labels:
    grafana_dashboard: "1"
  annotations:
    k8s-sidecar-target-directory: "/tmp/dashboards/inventory"
data:
{{ (.Files.Glob "custom-dashboards/inventory/*.json" ).AsConfig | indent 2 }}
